name: onlineoffice_flutter
description: App Onine Office.

# Command line build android: C:\flutter\bin\flutter.bat --no-color build appbundle

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+2

environment:
  sdk: ">=1.22.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_udid: ^1.0.1
  crypto: ^2.1.3
  http: ^0.12.0+4
  local_auth: ^0.6.2+3
  shared_preferences: ^0.5.6+3
  firebase_messaging: ^7.0.3
  flutter_app_badger: ^1.1.2
  flutter_local_notifications: ^4.0.1+2
  # flutter_local_notifications: ^1.4.4+1
  date_format: ^1.0.8
  # if (date == null) return '';
  datetime_picker_formfield: ^1.0.0
  flutter_widget_from_html: ^0.3.2+2
  dio: ^3.0.9
  flutter_full_pdf_viewer: ^1.0.6
  flutter_plugin_pdf_viewer: ^1.0.7
  open_file: ^3.0.3
  file_picker: ^1.13.3
  # recode with last version  
  image_picker: ^0.6.7+17
  multi_image_picker: ^4.7.14
  flutter_webview_plugin:
    git:
      url: https://github.com/hnguyen48206/flutter_webview_plugin.git
      ref: my0.3.11
  # iOS => ~/Dropbox/OnlineOffice_AppV2/Flutter_App/flutter_webview_plugin_Fix_Error_Show_Dialog_iOS.txt
  # Android => C:\Flutter\.pub-cache\hosted\pub.dartlang.org\flutter_webview_plugin-{{version}}\android\src\main\java\com\flutter_webview_plugin\WebviewManager.java => replace '\.fileprovider' to '\.fileProvider' 
  esys_flutter_share: ^1.0.2
  photo_view: ^0.10.3
  pull_to_refresh: 1.6.3
  mime_type: ^0.3.2
  flutter_search_bar: ^2.1.0
  flutter_slidable: ^0.5.7
  #line_icons: ^1.3.2
  rxdart: ^0.21.0
  # threading: ^0.0.10
  need_resume: ^1.0.4

   
  #flutter_search_bar:
  #  git:
  #    url: https://github.com/ArcticZeroo/flutter-search-bar.git
  # flutter_search_bar_base.dart => buildSearchBar(...) => TextField(...) => add property 'textAlign: TextAlign.right'


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - images/background_login.jpg
    - images/logo_150.jpg
    - images/background_chat.jpeg
    - images/img_not_available.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages