name: onlineoffice_flutter
description: App Onine Office.

# Command line build android: C:\flutter\bin\flutter.bat --no-color build appbundle

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+2

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter_udid: ^2.0.1
  crypto: ^3.0.2
  http: ^0.13.5
  local_auth: ^2.1.2
  shared_preferences: ^2.0.15
  firebase_messaging: ^14.1.1
  flutter_app_badger: ^1.5.0
  flutter_local_notifications: ^12.0.3+1
  # flutter_local_notifications:
  #   git:
  #     url: https://github.com/hnguyen48206/local_noti_flutter_fork.git
  #     ref: fix_indirect
  # flutter_local_notifications: ^1.4.4+1
  date_format: ^2.0.7
  # if (date == null) return '';
  datetime_picker_formfield: ^2.0.1
  flutter_widget_from_html: ^0.9.1
  dio: ^4.0.6
  # flutter_full_pdf_viewer: ^1.0.6
  # flutter_plugin_pdf_viewer: ^1.0.7
  easy_pdf_viewer: ^1.0.6
  open_file: ^3.2.1
  file_picker: ^4.6.1
  # recode with last version  
  image_picker: ^0.8.6
  multi_image_picker: ^4.8.01
  flutter_webview_plugin:
    git:
      url: https://github.com/hnguyen48206/flutter_webview_plugin.git
      ref: master
  webview_flutter: ^4.2.2
  internet_file: ^1.2.0

  # flutter_webview_plugin: ^0.4.0
  # iOS => ~/Dropbox/OnlineOffice_AppV2/Flutter_App/flutter_webview_plugin_Fix_Error_Show_Dialog_iOS.txt
  # Android => C:\Flutter\.pub-cache\hosted\pub.dartlang.org\flutter_webview_plugin-{{version}}\android\src\main\java\com\flutter_webview_plugin\WebviewManager.java => replace '\.fileprovider' to '\.fileProvider' 
  # esys_flutter_share: ^1.0.2
  esys_flutter_share_plus: ^2.2.0
  photo_view: ^0.14.0
  pull_to_refresh: ^2.0.0
  mime_type: ^1.0.0
  flutter_search_bar: ^3.0.0-dev.1
  flutter_slidable: ^2.0.0
  #line_icons: ^1.3.2
  rxdart: ^0.27.7
  # threading: ^0.0.10
  need_resume: ^1.0.7+1
  diacritic: ^0.1.3
  firebase_core: ^2.3.0
  move_to_background: ^1.0.2

  #flutter_search_bar:
  #  git:
  #    url: https://github.com/ArcticZeroo/flutter-search-bar.git
  # flutter_search_bar_base.dart => buildSearchBar(...) => TextField(...) => add property 'textAlign: TextAlign.right'


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - images/background_login.jpg
    - images/logo_150.jpg
    - images/background_chat.jpeg
    - images/img_not_available.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages